apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-sample-r-app-deployment-${TESTING_ID}
  namespace: dotnet-sample-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-remote-app
  strategy: {}
  template:
    metadata:
      labels:
        app: dotnet-remote-app
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: "true"
    spec:
      containers:
        - name: dotnet-remote
          image: ${IMAGE}
          env:
            - name: LISTEN_ADDRESS
              value: "0.0.0.0:8081"
            - name: ASPNETCORE_URLS
              value: "http://+:8081"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://cloudwatch-agent.amazon-cloudwatch:4316"
            - name: OTEL_DOTNET_AUTO_PLUGINS
              value: "AWS.Distro.OpenTelemetry.AutoInstrumentation.Plugin, AWS.Distro.OpenTelemetry.AutoInstrumentation"
          ports:
            - containerPort: 8081
      imagePullSecrets:
        - name: ecr-secret