## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: Apache-2.0

## This workflow aims to run the Application Signals Python end-to-end tests as a canary to
## test the artifacts for Application Signals enablement. It will deploy a sample app and remote
## service onto an EKS cluster, call the APIs, and validate the generated telemetry,
## including logs, metrics, and traces.
name: App Signals Enablement - Tests Python E2E EKS Canary Testing
on:
#  schedule:
#    - cron: '*/15 * * * *' # run the workflow every 15 minutes
  workflow_dispatch: # be able to run the workflow on demand
  push:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read


jobs:
  python-e2e-eks-test:
    strategy:
      fail-fast: false
      matrix:
        aws-region: ['af-south-1']
    uses: ./.github/workflows/application-signals-python-e2e-eks-test.yml
    secrets: inherit
    with:
      aws-region: ${{ matrix.aws-region }}
      test-cluster-name: 'e2e-python-canary-test'
      caller-workflow-name: 'appsignals-python-e2e-eks-canary-test'
