## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: Apache-2.0

## This workflow aims to run the Application Signals end-to-end tests as a canary to
## test the artifacts for App Signals enablement. It will deploy a sample app and remote
## service on two EC2 instances, call the APIs, and validate the generated telemetry,
## including logs, metrics, and traces.
name: Java EC2 Enablement Canary Testing
on:
  # schedule:
  #   - cron: '6,31 * * * *' # run the workflow at 6th and 31th minute of every hour
  push:
  workflow_dispatch: # be able to run the workflow on demand

permissions:
  id-token: write
  contents: read

jobs:
  github:
    strategy:
      fail-fast: false
      matrix:
        aws-region: ['us-east-1']
    uses: ./.github/workflows/java-ec2-default-retry.yml
    secrets: inherit
    with:
      aws-region: ${{ matrix.aws-region }}
      caller-workflow-name: 'appsignals-e2e-ec2-canary-test'
      java-version: '11'
      cpu-architecture: 'x86_64'
      operating-system: 'al2'

  maven:
    uses: ./.github/workflows/java-ec2-default-retry.yml
    secrets: inherit
    with:
      aws-region: 'us-east-1'
      caller-workflow-name: 'appsignals-e2e-ec2-maven-canary-test'
      otel-source: 'maven'
      java-version: '11'
      cpu-architecture: 'x86_64'
