## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: Apache-2.0

## This workflow aims to run the Application Signals end-to-end tests as a canary to
## test the artifacts for App Signals enablement. It will deploy the CloudWatch Agent
## Operator and our sample app and remote service onto a native K8s cluster, call the
## APIs, and validate the generated telemetry, including logs, metrics, and traces.
## It will then clean up the cluster and EC2 instance it runs on for the next test run.
name: Java K8s E2E Canary Testing
on:
  schedule:
    - cron: '*/15 * * * *' # run the workflow every 15 minutes
  workflow_dispatch: # be able to run the workflow on demand

permissions:
  id-token: write
  contents: read

jobs:
  k8s:
    uses: ./.github/workflows/java-k8s-e2e-test.yml
    secrets: inherit
    with:
      # To run in more regions, a cluster must be provisioned manually on EC2 instances in that region
      aws-region: 'us-east-1'
      caller-workflow-name: 'appsignals-e2e-k8s-canary-test'