## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: Apache-2.0

name: Sample App Deployment - Python S3
on:
  workflow_dispatch: # be able to run the workflow on demand
  push:
    branches:
      - python-genesis-app-metrics-fix

permissions:
  id-token: write
  contents: read

env:
  E2E_TEST_ACCOUNT_ID: ${{ secrets.APPLICATION_SIGNALS_E2E_TEST_ACCOUNT_ID }}
  E2E_TEST_ROLE_NAME: ${{ secrets.APPLICATION_SIGNALS_E2E_TEST_ROLE_NAME }}

jobs:
  python-zip:
    strategy:
      fail-fast: false
      matrix:
        aws-region: [ 'af-south-1','ap-east-1','ap-northeast-1','ap-northeast-2','ap-northeast-3','ap-south-1','ap-south-2','ap-southeast-1',
                      'ap-southeast-2','ap-southeast-3','ap-southeast-4','ca-central-1','eu-central-1','eu-central-2','eu-north-1',
                      'eu-south-1','eu-south-2','eu-west-1','eu-west-2','eu-west-3','il-central-1','me-central-1','me-south-1', 'sa-east-1',
                      'us-east-1','us-east-2', 'us-west-1', 'us-west-2' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.E2E_IAD_TEST_ACCOUNT_ARN }}
          aws-region: us-east-1

      - name: Retrieve account
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids:
            ACCOUNT_ID, region-account/${{ matrix.aws-region }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/${{ secrets.E2E_TEST_ROLE_ARN }}
          aws-region: ${{ matrix.aws-region }}

      # - name: Build Sample App Zip
      #   working-directory: sample-apps/python
      #   run: zip -r python-sample-app.zip .

      # - name: Upload to S3
      #   working-directory: sample-apps/python
      #   run: aws s3api put-object --bucket ${{ secrets.APP_SIGNALS_E2E_EC2_JAR }}-prod-${{ matrix.aws-region }} --body ./python-sample-app.zip --key python-sample-app.zip

      # - name: Build Lambda Sample App
      #   uses: actions/checkout@v4
      #   with:
      #     repository: 'aws-observability/aws-otel-python-instrumentation'
      # - name: Build sample lambda function
      #   shell: bash
      #   run: ./package-lambda-function.sh
      #   working-directory: lambda-layer/sample-apps

      # - name: Upload to Lambda Sample App to S3
      #   working-directory: lambda-layer/sample-apps
      #   run: aws s3api put-object --bucket ${{ secrets.APP_SIGNALS_E2E_EC2_JAR }}-prod-${{ matrix.aws-region }} --body ./build/function.zip --key pyfunction.zip

      # - name: Build Sample App Zip
      #   working-directory: sample-apps/python
      #   run: zip -r python-sample-app.zip .

      # - name: Upload to S3
      #   working-directory: sample-apps/python
      #   run: aws s3api put-object --bucket ${{ secrets.APP_SIGNALS_E2E_EC2_JAR }}-prod-${{ matrix.aws-region }} --body ./python-sample-app.zip --key python-sample-app.zip

      - name: Build Gen AI Sample App Zip
        working-directory: sample-apps/python-gen-ai
        run: zip -r python-gen-ai-sample-app.zip .

      - name: Upload Gen AI Sample App to S3
        working-directory: sample-apps/python-gen-ai
        run: aws s3api put-object --bucket ${{ secrets.APP_SIGNALS_E2E_EC2_JAR }}-prod-${{ matrix.aws-region }} --body ./python-gen-ai-sample-app.zip --key python-gen-ai-sample-app.zip

